In [18]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import load_iris

In [19]:
df1 = pd.read_csv(r"C:\Users\91898\Downloads\iris.csv")
df1

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [20]:
df = df1[(df1["variety"] == 'Setosa') | (df1["variety"] == 'Versicolor')]
df['class'] = np.where(df["variety"] == 'Setosa', 0, 1)     # If variety is Setosa give '0' Else give '1'
df = df.drop(columns=['variety'])
df['bias']=1

In [21]:
df

    sepal.length  sepal.width  petal.length  petal.width  class  bias
0            5.1          3.5           1.4          0.2      0     1
1            4.9          3.0           1.4          0.2      0     1
2            4.7          3.2           1.3          0.2      0     1
3            4.6          3.1           1.5          0.2      0     1
4            5.0          3.6           1.4          0.2      0     1
..           ...          ...           ...          ...    ...   ...
95           5.7          3.0           4.2          1.2      1     1
96           5.7          2.9           4.2          1.3      1     1
97           6.2          2.9           4.3          1.3      1     1
98           5.1          2.5           3.0          1.1      1     1
99           5.7          2.8           4.1          1.3      1     1

[100 rows x 6 columns]

In [22]:
# 80-20 SPLIT OF THE DATASET
dfTrain = pd.concat([df.iloc[0:40], df.iloc[50:90]]).reset_index(drop=True)
dfTest = pd.concat([df.iloc[40:50], df.iloc[90:100]]).reset_index(drop=True)

In [23]:
a=np.array([0,0,0,0,0]) # INITIAL WEIGHT VECTOR
learningRate=0.0001 # LEARNING RATE
epochs=100 # MAX ITERATIONS

In [25]:
#TRAINING THE PERCEPTRON
for it in range(epochs):
    mse=0
    for i in range (len(dfTrain)):
        W=np.array([dfTrain.loc[i,'sepal.length'],dfTrain.loc[i,'sepal.width'],dfTrain.loc[i,'petal.length'],dfTrain.loc[i,'petal.width'],dfTrain.loc[i,'bias']])
        if (a*W).sum() > 0:
            Output=1
        else:
            Output=0
        error=Output-dfTrain.loc[i,'class']
        a=a-learningRate*error*W
        mse+=error**2
    mse/=(len(dfTrain))
    print(f"Iteration {it+1}, MSE: {mse}")
    if mse==0: break

# FINAL WEIGHT VECTOR AFTER CONVERGENCE OF PERCEPTRON
print(f"The final Weight vector after convergence is {a}")

#TESTING THE PERCEPTRON
count=0
for i in range(len(dfTest)):
    W=np.array([dfTest.loc[i,'sepal.length'],dfTest.loc[i,'sepal.width'],dfTest.loc[i,'petal.length'],dfTest.loc[i,'petal.width'],dfTest.loc[i,'bias']])
    if (a*W).sum() > 0:
        Output=1
    else:
        Output=0
    if Output==dfTest.loc[i,'class']:
        count += 1

#ACCURACY
accuracy = count/len(dfTest) * 100
print(f"Accuracy on test set: {accuracy:.2f}%")

Iteration 1, MSE: 0.0125
Iteration 2, MSE: 0.0375
Iteration 3, MSE: 0.0125
Iteration 4, MSE: 0.0
The final Weight vector after convergence is [-0.00011 -0.00036  0.00052  0.00022 -0.0001 ]
Accuracy on test set: 100.00%